title:  Zhang Ziqi (ziki)'s Homepage
page-top-title: Ziqi Zhang ziki
top-section-bg-text: Welcome to ziki's homepage
home-subtitle: Zhang Ziqi, Ziki&ensp;|&ensp;张子奇
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
